# Generated by Django 5.1.3 on 2025-06-04 07:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mission', models.CharField(max_length=500)),
                ('vision', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='logo-images')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About Us',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': '',
                'ordering': ['-date_added'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_one', models.IntegerField(blank=True, null=True)),
                ('contact_two', models.IntegerField(blank=True, null=True)),
                ('contact_three', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Detail',
                'verbose_name_plural': 'Contact Details',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='executive_images')),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Executive',
                'verbose_name_plural': 'Executives',
                'db_table': '',
                'ordering': ['-date_posted'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery_images')),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
                'db_table': '',
                'ordering': ['-date_posted'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='slider_images')),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Hero',
                'db_table': '',
                'ordering': ['-date_posted'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='school_logo')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logo',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
