# Generated by Django 5.1.3 on 2025-06-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_activities_blog_offers_programs_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
    ]
