# Generated by Django 5.1.3 on 2025-06-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_blog_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='featured',
        ),
    ]
