# Generated by Django 5.1.3 on 2025-06-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_blogs_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='image',
            field=models.ImageField(default=1, upload_to='Activity Images'),
            preserve_default=False,
        ),
    ]
