# Generated by Django 5.1.3 on 2025-06-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_activities_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='date_added',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
