# Generated by Django 5.1.3 on 2025-06-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_activities_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_one',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_three',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='contact_two',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='primary_contact',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='secondary_contact',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
