# Generated by Django 5.1.3 on 2025-06-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_contact_contact_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
