# Generated by Django 5.1.3 on 2025-06-05 13:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_activities_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activities',
            options={'managed': True, 'ordering': ['-date_added'], 'verbose_name': 'Activities', 'verbose_name_plural': 'Activities'},
        ),
        migrations.RenameField(
            model_name='inbox',
            old_name='phone',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='inbox',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterUniqueTogether(
            name='activities',
            unique_together={('title', 'date_added')},
        ),
        migrations.AlterUniqueTogether(
            name='blogs',
            unique_together={('headline', 'date_posted')},
        ),
    ]
