# Generated by Django 5.1.3 on 2025-06-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='subject',
        ),
        migrations.AddField(
            model_name='teachers',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
