# Generated by Django 5.1.3 on 2025-06-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_teachers_stage_remove_teachers_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='religion',
        ),
    ]
